#!/bin/bash
echo "Waiting for atleast one device to connect"
NM=""
if [ $# -eq 1 -a $1 == "help" ]
then
	echo "Drozer Startup assistant"
	echo "Usage $0 [console]"
	echo "specify console if you want to get a drozer shell"
	echo "no option would result is drozer setup which cn then be used by other commands"
fi
if [ $# -gt 1 -a $1 != "console" ]
then
	echo "Device Specific request recieved"
	echo "Configuring ADB to send commands to device"
	NM=$1
	shift
fi
adb wait-for-devices
adb $NM shell am startservice -n com.mwr.dz/.services.ServerService -c com.mwr.dz.START_EMBEDDED
adb $NM forward tcp:31415 tcp:31415
if [ $1 == "console" ]
then
	drozer console connect
fi